### ISSUE TITLE
Distribution of Bequests

### ISSUE THREAD

**Issue by kerkphil** [PSLmodels/OG-USA#14]
Need to look into estimating the distribution of bequest from agent j,s,t who dies to agents next period over all types, j, and all ages, s,.

**Comment by jdebacker** [comment]
@rickecon Let us know what the progress is with this calibration using US data.

**Comment by rickecon** [comment]
@jdebacker @kerkphil . We have this. @parkerrogers wrote the initial code. I rewrote some of it. I'll post here soon. But this will require a change in the OG-USA theory that changes how OG-USA is computed.

**Comment by jdebacker** [comment]
@rickecon Great.

Is it really much more than changing [this line](https://github.com/open-source-economics/OG-USA/blob/90e17b5b9af30a79c314e25e30bcede744b0a6bc/ogusa/household.py#L135) in `household.py` (plus passing the `zeta_mat` object through the appropriate function calls to get here)?

**Comment by jdebacker** [comment]
Allowing for this bequest distribution process is now a feature of OG-USA with PR #438.  Work will still need to be done on the calibration, but this issue is now resolved.
