### ISSUE TITLE
Create smoothing file to centralize MVKDE function

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#25]
It's currently duplicated in

https://github.com/PSLmodels/OG-USA-Calibration/blob/283fa709f12d996a959b9a60facce3347c36cfa1/ogusa_calibrate/transfer_distribution.py#L10

and 

https://github.com/PSLmodels/OG-USA-Calibration/blob/283fa709f12d996a959b9a60facce3347c36cfa1/ogusa_calibrate/bequest_transmission.py#L10

**Comment by jdebacker** [comment]
The function was moved to the `utils.py` module to avoid duplication.
