### ISSUE TITLE
Enforce PEP 8 standards

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#303]
Mostly due to me, OG-USA is not compliant with PEP 8 standards.  We should fix this (as well as other code clean up noted in Issue #287.

**Comment by rickecon** [comment]
Let's put a PEP8 test in our Travis CI. This will require a massive effort to clean up the code to PEP 8 standards. @jdebacker @MattHJensen @PeterDSteinberg @hdoupe @jbcrail

**Comment by jdebacker** [comment]
I agree that we want to do this at some point.  But let's decide how strict we'll want to be, i.e., what [error codes](http://pep8.readthedocs.io/en/release-1.7.x/intro.html#error-codes) do we want to ignore?

e.g., Tax-Calc ignores E402.  @PeterDSteinberg suggested that sometimes the code is less readable if we enforce E501 strictly, etc.  

If folks have error codes they think it'd be worthwhile to ignore in a test for PEP8 compliance, let's have that discussion here.

**Comment by jdebacker** [comment]
Many modules have been updated to be PEP8 compliant.  This work will be on going, but for sometime now, contributors creating new scripts or editing existing ones have been improving the PEP8 compliance as other changes are made.

We are probably close to the point that it makes sense to have a PEP8 test.

**Comment by jdebacker** [comment]
We now have some PEP8 testing available and we are close to 100% compliant.  Closing.
