### ISSUE TITLE
Log warning messages

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#336]
Per suggestions from @hdoupe, use the `capture_warnings` function in the `logging` module to capture warning messages so they can be displayed on the output page in Policy Brain.

**Comment by hdoupe** [comment]
@jdebacker Sorry for moving slowly on this issue.  I thought about this some more.  I think your current solution of using the warning module to print the warning to stdout is good.  

However, I think it also makes sense to include a error/warning dictionary along with your results.  Tax-Calculator provides a dictionary of error and warning messages to PolicyBrain after doing input validation.  I think having a similar dictionary for model runs makes sense, too.

The Tax-Calculator dictionary looks like:
```
{
'errors':
    'ERROR: 2017 _FICA_ss_trt value -1.0 < min value 0\nERROR: 2018 _FICA_ss_trt value -1.0 < min value 0\n',
 'warnings': 
    'WARNING: 2020 _STD_3 value 150.0 < min value 9900.32\nWARNING: 2021 _STD_3 value 153.57 < min value 10138.33\n'
}
```

Does this seem sensible to you?

**Comment by jdebacker** [comment]
@hdoupe This does.  I appreciate this info - I can probably go from here, but I'll let you know if I have questions.

**Comment by jdebacker** [comment]
OG-USA currently has parameter validation via ParamTools, which logs errors and warning messages with parameter inputs.

This issue was in part opened to think about how runtime errors would be captured and displayed via  web apps like the old OSPC apps.  @hdoupe Do you have suggestions on how/if runtime errors need to be logged in a similar way - or is the the current approach of displaying a runtime error as is done [here](https://github.com/PSLmodels/OG-USA/blob/5d25d77a8204c2e38181fdbe694843767568fce4/ogusa/SS.py#L641) OK and informative enough for users of Compute Studio?

**Comment by hdoupe** [comment]
> OG-USA currently has parameter validation via ParamTools, which logs errors and warning messages with parameter inputs.

Yep, OG-USA's inputs validation looks good.

> This issue was in part opened to think about how runtime errors would be captured and displayed via web apps like the old OSPC apps. @hdoupe Do you have suggestions on how/if runtime errors need to be logged in a similar way - or is the the current approach of displaying a runtime error as is done here OK and informative enough for users of Compute Studio?

Throwing a `RunTime` error seems appropriate. Note that the error will get propagated back to C/S and the user will get a page like this: https://compute.studio/PSLmodels/Tax-Brain/42911/. I will then open an issue in the model's github repo and send the user who received the error an email kind of like this:

> We saw that you received an error on several of your PSLmodels/Tax-Brain simulations. I opened an issue addressing these errors in the Tax-Brain bug tracker (issue [#86](https://github.com/PSLmodels/Tax-Brain/issues/86)). We are working to resolve the issue.
> 
> I'm sorry for the inconvenience. Please write back if you have any questions or if there is anything else that we can do to help.
> 
> Best,
> Hank Doupe

**Comment by jdebacker** [comment]
@hdoupe thanks for the quick follow up.  I'm closing this issue.
