### ISSUE TITLE
Large open economy option

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#434]
We should include a simple large open economy option.  This will provide a middle ground between the close and small open economy options available now.

The degree of openness will be a parameter that represents the share of one of the following that are purchased by foreigners:

- New debt issues
- Total gov't debt outstanding
- Total demand for assets (gov't debt and firm demand for capital) 

Which makes the most sense?  I think several other similar models only have foreigners purchasing gov't debt - so domestic savers have to supply enough capital to cover firm demand, as well as some share of gov't debt.

If the parameter represents the fraction of total debt outstanding held by foreigners, we could use [this](https://fred.stlouisfed.org/series/HBFIGDQ188S) data series to help calibrate.

cc @rickecon

**Comment by kerkphil** [comment]
There is a very good paper on the type of assumptions one can make to force a single-country open-economy model to behave like a large open economy.  Here is the citation:  Schmitt-Grohe, Stephanie and Martın Uribe, "Closing small open economy models," Journal of International Economics, 2003, 61 (1), 163 - 185.

My preferred method is akin to the one they use in section 3, which is to model a wedge between domestic and foreign interest rates that is falling as the amount of foreign assets held by home agents as a percent of GDP rises.

One simple formula that works good in practice is $r_t = r - \nu \frac{B_t}{Y_t}$, where Bis the net holdings of foreign assets and could be negative if the country as a whole issues debt internationally.

Here's a link to a paper on Japanese immigration where I implemented this setup for two different types of households. (https://drive.google.com/file/d/1HhlqKgzAO2RE-LrSd903OHM5u0JW35PI/view)  See section 2.3.

@rickecon @jdebacker

**Comment by jdebacker** [comment]
Thanks for the suggestions @kerkphil!

**Comment by jdebacker** [comment]
This issue is resolved with PR #451
