### ISSUE TITLE
Use read_csv instead of read_table

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#440]
`pd.read_table` is deprecated, so this is throwing a warning, which can be avoided by replacing it with `pd.read_csv` (no `sep=','` is needed).

```
/home/maxghenis/OG-USA/ogusa/demographics.py:112: FutureWarning: read_table is deprecated, use read_csv instead.
  pop_data = pd.read_table(pop_file, sep=',', thousands=',')
/home/maxghenis/OG-USA/ogusa/demographics.py:273: FutureWarning: read_table is deprecated, use read_csv instead.
  mort_data = pd.read_table(mort_file, sep=',', thousands=',')
/home/maxghenis/OG-USA/ogusa/demographics.py:477: FutureWarning: read_table is deprecated, use read_csv instead.
  pop_data = pd.read_table(pop_file, sep=',', thousands=',')
/home/maxghenis/OG-USA/ogusa/demographics.py:725: FutureWarning: read_table is deprecated, use read_csv instead.
  pop_data = pd.read_table(pop_file, sep=',', thousands=',')
```

![image](https://user-images.githubusercontent.com/6076111/52032323-4e315280-24d5-11e9-9075-315c172dd681.png)

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for noting this issue.

**Comment by rickecon** [comment]
@jdebacker changed the `pd.read_table` to `pd.read_csv` in `demographics.py` in PR #442. However, we still need to test and change those in `labor.py` and `wealth.py` modules.

**Comment by jdebacker** [comment]
Yes, I did for get those two scripts.  They are not currently incorporated into OG-USA (or tested in any way) but they are both somewhat useful when we try to think about how some parameters should be calibrated.  Because of this, we may want to keep them in the repo and keep them up to date.

**Comment by rickecon** [comment]
PR #443 takes care of the `pd.read_table` references in `wealth.py` and `labor.py`. Thanks @MaxGhenis and @jdebacker.
