### ISSUE TITLE
Distribution of transfers

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#467]
Non-Social Security Government transfers should be modeled more explicitly.  A simple step in the right direction would be to allocate non-SS government transfers across age and lifetime income group in a way that is consistent with recent patterns in their distribution.  This could be done by calibrating a matrix, call it eta, that is of dimension SxJ, which represents the share of total non-SS transfers to each age and lifetime income group.

**Comment by rickecon** [comment]
This issue is solved by PR #479 (Transfers).
