### ISSUE TITLE
Clean up of txfunc.py

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#468]
The following could help to make `txfunc.py` more clear and concise:

- [x]  `beg_yr` and `start_yr` seem to refer to the same thing. If so, just use the same object name.
- [x] use or delete `plot_txfunc_v_data()`
- [x] `plot_full` and `plot_trunc` are both used in `plot_txfunc_v_data()`, but just one of these booleans is enough
- [x] Are `age_min` and `age_max` same as `s_min` and `s_max`? If so, use consistent names for the objects
- [x] `tpers` and `BW` appear to refer to the same thing.  Use just one of these names to refer to the number of periods in the budget window.
- [x] In `tax_func_loop` we don't need to create such big arrays and then return slice so those arrays.  We can just start with smaller arrays and return the whole thing.

**Comment by jdebacker** [comment]
4 of these have been addressed in PR #470

**Comment by duncanhobbs** [comment]
It looks like `s_min` and `s_max` are the minimum and maximum ages to estimate tax functions for and min_age and max_age are the minimum and maximum ages observed in the data. I think this is useful for cases where there are gaps in the age data that are filled in using other data estimates.

**Comment by jdebacker** [comment]
@duncanhobbs  Thanks for confirming that those variables are not duplicates.  This issue has been fully addressed.
