### ISSUE TITLE
Rename get_K to get_B

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#469]
With households holding both capital and government debt in their portfolios, the function get_K should be renamed to get_B to better relate that it aggregates households savings, which is distinct from the aggregate amount of capital.

**Comment by duncanhobbs** [comment]
Is the only thing you want to change the name of the function? 

Should the vector `get_B` returns still be called `K`?

**Comment by jdebacker** [comment]
@duncanhobbs  The function name should be changed and `B` returned instead of `K`.  In addition, all calls to this function throughout the model scripts (they may all be in `SS.py` and `TPI.py`) should be replaced as well as all references in the test scripts.  

When doing this, one should still be aware that there is a `firm.get_K` function that should not be renamed or changed.

**Comment by duncanhobbs** [comment]
Thanks @jdebacker.

I will leave the `firm.get_K` function alone.

A few questions:

1) References to `K_d` and `K_f` should be left as is because they represent the domestic and foreign supply of aggregate capital. Is that correct?

2) In `TPI.py`  there are several instances of `K_init` as well as `B_init`. Should these be left as is as well?

**Comment by jdebacker** [comment]
@duncanhobbs 

> References to K_d and K_f should be left as is because they represent the domestic and foreign supply of aggregate capital. Is that correct?

Yes, that's correct.  I think other than the name of the function as `get_K`, all objects from it are appropriately named `B`.

>In TPI.py there are several instances of K_init as well as B_init. Should these be left as is as well?

Yes, leave those as well.

Thanks!

**Comment by jdebacker** [comment]
Closed with the merge of PR #471 by @duncanhobbs
