### ISSUE TITLE
Use ParamTools

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#491]
OG-USA should swap out the use of the custom `parametersbase.py` script and instead use the `Parameters` class from [ParamTools](https://github.com/PSLmodels/ParamTools).

This will make it easier to adopt OG-USA to [Compute Studio](https://www.compute.studio).

**Comment by hdoupe** [comment]
@jdebacker this sounds great. Let me know if there's anything that I can do to help. 

One thing that I need to do is add this kind of validation:

```json
{
    "range": {"min": 0, "max": "ending_age - 1"}
}
```

with the minus signs and other operators like that. I'm happy to do that. It'll be a good feature for ParamTools.

**Comment by jdebacker** [comment]
@hdoupe I can start working on changing the parameter validation etc over to ParamTools and we can add that later.  Just let me know when that feature is available.  Thanks!

**Comment by jdebacker** [comment]
Resolved with PR #494
