### ISSUE TITLE
Create Compute Studio app for OG-USA

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#492]
OG-USA should run on [Compute Studio](https://www.compute.studio).

**Comment by hdoupe** [comment]
I can't wait for OG-USA to have a webapp. Taking care of #491 first should make this straightforward. @MattHJensen suggested just doing steady state calculations while we are getting started. Does that seem reasonable?

Let me know if there's anything I can do to help out with this.

**Comment by jdebacker** [comment]
@hdoupe Yes, good idea to start with the steady-state calculations to make sure everything is up and running smoothly.

**Comment by jdebacker** [comment]
@hdoupe Do I need an `ogusa` package on Anaconda to get things working on Compute Studio?   I've had some trouble building an `ogusa` package with Package Builder lately...

**Comment by hdoupe** [comment]
Nope, Tax-Cruncher is installed with git: https://github.com/PSLmodels/Tax-Cruncher/blob/master/compconfig/install.sh

**Comment by jdebacker** [comment]
@hdoupe Great!  I'll get the Compute Studio stuff up before I mess with Package Builder again!

**Comment by jdebacker** [comment]
Resolved with PR #496.  Thanks for the help @hdoupe !
