### ISSUE TITLE
Travis CI not being triggered

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#512]
Travis CI seems to not be working although it looks like the webhook is ok.  This seemed to start about 3 days ago mid-PR. 

Need to resolve this...

cc @rickecon

**Comment by jdebacker** [comment]
I'm seeing the following under Settings -> Integration & Services:

> Note: GitHub Services have been deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps.

I'm unable to find a webhook on Travis CI because although I seem to be a member of the PSL organization, I do not see OG-USA as one of the repos in my dashboard.

Can someone fix Travis CI for OG-USA and/or advise me on how I can request permission to add the OG-USA repo to those I had admin rights to on Travis CI?

Thanks!

cc @rickecon @MattHJensen  @hdoupe

**Comment by hdoupe** [comment]
@jdebacker I just migrated OG-USA to use github apps from this URL: https://travis-ci.com/organizations/PSLmodels/repositories

It looks like most of the projects created recently like Tax-Cruncher are already using GitHub apps. A few others like OG-USA and Tax-Calculator are using GitHub services. I only migrated ParamTools and OG-USA for now. I can migrate the rest if this resolves the issue for OG-USA.

@MattHJensen @Peter-Metz can you double check the PSLmodels travis account to make sure I didn't change the travis-ci billing or something like that.

**Comment by jdebacker** [comment]
Thanks @hdoupe !  You solved the OG-USA issue!
