### ISSUE TITLE
Get data files from web

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#514]
This issue is a proposed solution to the goal of not storing data in the OG-USA repository. Much of the data we want to use for calibration is already accessible on the web. PR #511  adds the [`wealth.py`](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/wealth.py) module. This module uses Survey of Consumer Finances data in lines 21-22. We want to avoid loading that data in the repository.

This issue proposes to write code using the `requests` and `urllib.request` packages to give the user an option to have the data file locally or to get it from the SCF website. Examples of what I have in mind were written by @hayleefay in the [`hrs_by_age.py`](https://github.com/OpenSourceEcon/CPS_hrs_age/blob/master/hrs_by_age.py) file of the [`CPS_hrs_age`](https://github.com/OpenSourceEcon/CPS_hrs_age) module.

@jdebacker

**Comment by jdebacker** [comment]
Yes - can you can pass a url directly to the `Pandas.read_csv` (and `read_stata`, `read_excel`, etc) function as well.

**Comment by rickecon** [comment]
Many data files that we need to retrieve are zipped. The code updates in PR #517 deal with retrieving zipped files.
