### ISSUE TITLE
OG-USA logo proposals

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#520]
@jdebacker. I wanted to start a discussion about OG-USA logo proposals. Here is my first offering.

The short version
![OGUSAlogo_short](https://user-images.githubusercontent.com/4317690/68732595-412bae80-0591-11ea-8bf6-de70ac0e955a.png)

The long version
![OGUSAlogo_long](https://user-images.githubusercontent.com/4317690/68732612-4d177080-0591-11ea-9126-80e6c3da0f5f.png)

**Comment by jdebacker** [comment]
Took me a second to get the OG reference in there, but I like the short version!  Don't think we need that longer version with subtitle.  Thanks @rickecon for taking a stab at this.

**Comment by rickecon** [comment]
Do you want me to put some color in the circles, change any sizes or proportions or fonts? I want this logo for C/S as well as any other marketing that we do with it.

**Comment by rickecon** [comment]
@jdebacker Here are two variations with red circles.

![OGUSAlogo_Rick](https://user-images.githubusercontent.com/4317690/69092252-36e23800-0a09-11ea-9278-01fef4d5658b.png)

**Comment by jdebacker** [comment]
@rickecon Go Dawgs!

While I am partial to those colors given my undergrad alma mater, Maybe we need some red-white-blue scheme for OG-USA?

**Comment by rickecon** [comment]
@jdebacker Here are two options with red white and blue. I like this first one with the flag in a top circle, surrounded by five neutral-color circles that would be the same for any country.

![OGUSAlogo_Rickflag](https://user-images.githubusercontent.com/4317690/69108192-33fb3d80-0a31-11ea-9059-58c94272829e.png)

This second option is a little bit over-the-top with red, white, and blue circles. I don't like this second one very much.

![OGUSAlogo_RickRWB](https://user-images.githubusercontent.com/4317690/69108260-58571a00-0a31-11ea-85e5-522d79d541cf.png)

**Comment by jdebacker** [comment]
I like the flag ones, but I don't know how that detail will show up on different sized versions of this.  If we can retain more detail than in the images above, I'd feel better about it.  Here's a version without the colored dots that I like:

![OG-USA logo_jmd](https://user-images.githubusercontent.com/10715924/69114314-0de69500-0a53-11ea-96b1-edf3b8e2e89a.png)

I also don't mind the red/white/blue dots with white background that you have above.

**Comment by rickecon** [comment]
@jdebacker . Alright, finalists. So the two logos in the right column were your favorite and the two logos in the left column were my favorite. In truth, I could be happy with any of these four logos.

![OGUSAlogo_finalists](https://user-images.githubusercontent.com/4317690/69125125-55285200-0a62-11ea-9f11-1d667707f2d0.png)

Now, seeing them all together, if I had to rank order my preferences for those four (1=favorite, 4=least favorite), I would choose the following.
1. (upper left) Flag circle with neutral blue fill in the other five circles with white background. I like the neutral blue color. I think it would be good to have some color that can be constant across models. And I like this slightly better than the upper-right logo because the white circles seem a little bit empty to me.
2. (upper right) Flag circle with white fill in other five circles with white background. I like this one. My only complaint is the white background in the five non-flag circles.
3. (lower left) Flag circle with neutral blue fill in the other five circles with black background. I kind of like the black background, but really only as an alternative to the white background.
4. (lower right) I don't love the red/white/blue dots logo. It looks a little too colorful to me. The colors seem too prominent.

For different economy versions of the model (country and state), we would change the three-letter country code (or two-letter state code) at the end of the model name and add either a circular version of that country's (state's) flag in the three flag option logos or the colors of that state's flag inside the circles of the lower left logo.

I am happy to go with whatever logo is @jdebacker's top choice, but I would like to see @jdebacker's preference ordering and compare it with my preference ordering and try to choose the one that maximizes the sum of our welfare.

**Comment by jdebacker** [comment]
Agree about potential for too much color.  Here's one that tones it down a bit:

![OG-USA logo_jmd](https://user-images.githubusercontent.com/10715924/69189197-eabbf400-0aeb-11ea-9caf-98ccc6c920e8.jpg)

**Comment by rickecon** [comment]
OK. In discussion with @jdebacker, we have agreed for now to use the logo below for OG-USA. We decided to remove the border. We can replace this logo in the future, but for now we are moving ahead with this.

![OG-USA_logo_final](https://user-images.githubusercontent.com/4317690/69265475-8f8b0f80-0b86-11ea-8dac-38019759042b.png)

**Comment by rickecon** [comment]
One note and question for @jdebacker. The GitHub suggested template for a logo (called "social preview") is the following. For our GitHub logo that gets shown for any social media links do we want to include the descriptive text below the logo as we tried in the second image in the first post of this issue?
![repository-open-graph-template](https://user-images.githubusercontent.com/4317690/69267994-86507180-0b8b-11ea-8ec5-e690e7db51ad.png)
Also, this suggests that we should have a GitHub version of our logo with a 40pt border around it so that nothing gets cropped--regardless of whether or not we include descriptive text.

This is what it currently looks like in Twitter when we provide the link to the repository ([link to tweet](https://twitter.com/RickEcon/status/1197225896580542465)).
<img width="484" alt="Screen Shot 2019-11-20 at 11 51 46 AM" src="https://user-images.githubusercontent.com/4317690/69268382-41790a80-0b8c-11ea-9b82-bfe00ddffb2d.png">
This logo with text underneath would be the following.
![OG-USA_logo_long_final](https://user-images.githubusercontent.com/4317690/69269103-90736f80-0b8d-11ea-94d9-0afc6d5de808.png)
I think I prefer this long version with text underneath only for the GitHub social preview, then the stand-alone logo that we already decided on as the logo. Let me know what you think.

**Comment by rickecon** [comment]
@jdebacker Nevermind my previous comment. I tested the social preview with text below, and it gets cutoff in the preview, even if I leave space around all the edges. Let's stick with the simple logo for GitHub and for everywhere else.

**Comment by rickecon** [comment]
The method and steps for creating the logo was the following.
1. Create the logo in Google Draw
2. Download the logo as scalable vector graphics `.svg`
3. Open the `.svg` file of the logo in Photoshop
4. Make edits in Photoshop and save as both Photoshop file `.psd` and as portable network graphics file `.png`.

**Comment by rickecon** [comment]
@jdebacker . @kerkphil gave an interesting suggestion on Twitter that we should put the flag in one of the middle two circles. Below are two examples with each option. I think I like the first option best with the flag closest to the country abbreviation. And I think I like this better than what we had with the flag in the upper-right-most circle. Thoughts?
![OGUSAlogo_midflag](https://user-images.githubusercontent.com/4317690/69278725-20bab000-0ba0-11ea-9a41-454c4cde9499.png)

**Comment by jdebacker** [comment]
Ok - I do like the flag in the middle bar better.  Kind of indifferent between those two options though - it's nice when it comes first, reading left to right, but also makes sense by the country abbreviation.

**Comment by rickecon** [comment]
OK. I think I am now leaning toward the flag closer to "OG" in the first circle. Done. Thanks @kerkphil.
<img width="520" alt="Screen Shot 2019-11-20 at 3 29 34 PM" src="https://user-images.githubusercontent.com/4317690/69283916-99266e80-0baa-11ea-860b-61a8e2221833.png">
