### ISSUE TITLE
Precompute and store txfunc .pkl files

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#524]
Because estimating the tax function parameters from the microsimulation model in `txfunc.py` takes a significant amount of computation time, this issue proposes to precompute the baseline estimated tax functions for various start years and for both the proprietary IRS Public Use File (PUF) and for the publicly available with OG-USA Current Population Survey (CPS) file. These `.pkl` files take very little hard drive space, and each represents at least an hour of computation time.

I propose that we store these files in a new `OG-USA/ogusa/data/txfuncs/` directory. @jdebacker

**Comment by jdebacker** [comment]
Relatedly, besides caching some precomputed tax functions in the repo, let's also allow the user to pass a path to where the tax functions they want to use are stored, if `run_micro=False`.

**Comment by jdebacker** [comment]
These precomputed tax functions were added in PR #544.
