### ISSUE TITLE
Inconsistent usage of periods in Compute Studio parameter descriptions

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#567]
e.g. the top 4 here don't use a period while bottom 2 do
![image](https://user-images.githubusercontent.com/6076111/81976657-ba0dd080-95dd-11ea-90f5-4cc167645635.png)

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for noticing this.  Let's drop any periods in the `title` field in `default_parameters.json`, but keep it in the description and notes fields, where appropriate.

**Comment by MaxGhenis** [comment]
>Let's drop any periods in the title field in default_parameters.json, but keep it in the description and notes fields, where appropriate.

Done in new commits in #568. There wasn't a clear pattern of which description and notes fields had periods (some sentence fragments did, some full sentences didn't) so I added periods to all of them.

**Comment by rickecon** [comment]
Thanks @MaxGhenis.
