### ISSUE TITLE
Unclear behavior in CS for params that can have dims added

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#611]
I'm not sure if this is intended, but any params specifies with `"number_dims": 1` have plus and minus buttons in CS to add more rows/dimensions to that param. TFP is the topmost parameter in CS to have this:

![image](https://user-images.githubusercontent.com/6076111/89251935-2c82c100-d5cd-11ea-898e-d3ce47383b29.png)

After hitting + twice, it becomes:
![image](https://user-images.githubusercontent.com/6076111/89251952-3c020a00-d5cd-11ea-8ef0-d5bbc5f14517.png)

I'm trying this out in https://compute.studio/PSLmodels/OG-USA/142 now to see what happens.

Relevant code:

https://github.com/PSLmodels/OG-USA/blob/1fbdd0cff4124bee3033cf0f9076c92daf636559/ogusa/default_parameters.json#L259-L266

cc @hdoupe

**Comment by jdebacker** [comment]
@MaxGhenis Yes, this is intended.  Each value entered applies to a different year, with the first value corresponding to the start year.

**Comment by MaxGhenis** [comment]
> @MaxGhenis Yes, this is intended. Each value entered applies to a different year, with the first value corresponding to the start year.

Ah, so does adding a second dim change the value at `start_year+1`?

This might be useful info for the hover info text.

**Comment by jdebacker** [comment]
> This might be useful info for the hover info text.

Yes, it would be.

**Comment by MaxGhenis** [comment]
https://compute.studio/PSLmodels/OG-USA/142 produced the two below charts, raising a couple questions:
1. Why did consumption change? Setting another row for TFP with the same value (1) shouldn't have changed anything right? The economic aggregates didn't change.
2. [Probably separate from this issue] Why is a different set of charts being shown for this one compared to tax reforms? Is there a way to view the consumption distributional chart in tax reform experiments?
![image](https://user-images.githubusercontent.com/6076111/89327172-532e0f80-d640-11ea-8f1c-2bbd131d3345.png)
![image](https://user-images.githubusercontent.com/6076111/89327307-96887e00-d640-11ea-9bf6-382c8318355e.png)

**Comment by jdebacker** [comment]
@MaxGhenis:

1.  We can only display a few charts, so we've selected a different set for the SS than the transition path results.
2. Consumption didn't change (in any meaningful way) - look at the scale in that plot.

**Comment by jdebacker** [comment]
Addressed in PR #668.
