### ISSUE TITLE
Jupyter-book documentation issues

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#613]
This looks really good! Nice upgrade from the pdf. I imagine some of this is already known, but wanted to just note some minor issues I saw when going through it:
- [x] Non-footnote footnote in [contributor guide](http://pslmodels.github.io/OG-USA/content/contributing/contributor_guide.html#simple-usage)

![image](https://user-images.githubusercontent.com/6076111/89490477-cbd8bd00-d761-11ea-914e-d0ebd4e0a265.png)

- [ ] Unlinked/unbulleted sections at bottom of [API](http://pslmodels.github.io/OG-USA/content/api/public_api.html)
![image](https://user-images.githubusercontent.com/6076111/89490559-004c7900-d762-11ea-88f0-5f7eebd4f2d3.png)

- [x] Label in [model overview](http://pslmodels.github.io/OG-USA/content/theory/intro.html)
![image](https://user-images.githubusercontent.com/6076111/89490657-37bb2580-d762-11ea-9d63-c260420c59b6.png)

- [x] Theory subchapter headings have links. Not sure if this was intentional but it's not done elsewhere in the book, and clicking them doesn't scroll to the section, unlike the built-in paragraph markers (e.g. [this](http://pslmodels.github.io/OG-USA/content/theory/households.html#SecHHBC) vs [this](http://pslmodels.github.io/OG-USA/content/theory/households.html#budget-constraint)). I see they're used elsewhere for cross-linking, so an option there could be just adding the cross link marker without linking it.
![image](https://user-images.githubusercontent.com/6076111/89491562-6508d300-d764-11ea-80ad-3893afdc73df.png)

- [x] Fig 1 [here](http://pslmodels.github.io/OG-USA/content/theory/households.html#elliptical-disutility-of-labor-supply) doesn't show up.
![image](https://user-images.githubusercontent.com/6076111/89491869-160f6d80-d765-11ea-89a2-6731524b418c.png)

- [x] The EvansPhillips:2017 ref doesn't render in 2 places [here](http://pslmodels.github.io/OG-USA/content/theory/households.html#elliptical-disutility-of-labor-supply)

- [x] A number of cross-references aren't linking in [Households](http://pslmodels.github.io/OG-USA/content/theory/households.html), e.g. SecHHellipUtil and Chap_Calibr, as well as ref DefNSSEql.

- [ ] Last paragraph in [Firms](http://pslmodels.github.io/OG-USA/content/theory/firms.html) has a couple issues:
![image](https://user-images.githubusercontent.com/6076111/89492082-97ff9680-d765-11ea-9871-c622e95fdd28.png)

- [x] "(Chap_UnbalGBC)" at the top of [Government](http://pslmodels.github.io/OG-USA/content/theory/government.html).

- [x] I think `[TabStnrzStatVars]Stationary variable definitions` is intended to be a heading in [Stationarization](http://pslmodels.github.io/OG-USA/content/theory/stationarization.html).

- [x] A few equations aren't linking in [Stationarization](http://pslmodels.github.io/OG-USA/content/theory/stationarization.html) (search for `{eq}`).

- [x] A number of TeX errors and broken links in [Equilibrium](http://pslmodels.github.io/OG-USA/content/theory/equilibrium.html)

- [x] [Exogenous Parameters](http://pslmodels.github.io/OG-USA/content/calibration/exogenous_parameters.html) has ` \texttt{parameters.py}` and `[TabExogVars]List of exogenous parameters and baseline calibration values`

- [x] Some TeX in [Demographics](http://pslmodels.github.io/OG-USA/content/calibration/demographics.html), especially `citet{}`s.

- [x] Unlinked sections at the bottom of [Immigration rates](http://pslmodels.github.io/OG-USA/content/calibration/demographics.html#immigration-rates)

- [x] [Lifetime Earnings Profiles](http://pslmodels.github.io/OG-USA/content/calibration/earnings.html) has `[PikettySaez:2003]` and `[DeBackerRamnath:2017]`

- [x] Lifetime Earnings Profiles has `##Continuous Work History Sample`, `\footnote{`, and `[tab:wage_step1]Initial Log Wage Regressions`.

- [x] Citations in [Bequest Process Calibration](http://pslmodels.github.io/OG-USA/content/calibration/bequests.html) don't render. Also not sure if there's missing info here? And this is the only Calibration sub-chapter that also states "Calibration", so may be redundant.

- [x] `\citet`s and `Chapter ???` in [Derivations](http://pslmodels.github.io/OG-USA/content/theory/derivations.html)

**Comment by jdebacker** [comment]
@MaxGhenis We were aware that a number of issues remain in the documentation, but we thought it easier to merge in my in progress work to get other contributors to improving it.  I appreciate you outlining a number of specific issues that need to be addressed.

A couple comments:
* When I build locally, the figures that are generated using embedded excitable code build, but they do not seem to have built via the GitHub action building the book.
* When I built locally, I thought it worked ok to have both a `references.bib` (which listed cited references in the References chapter) and a `citations.bib` (which listed citations in the Citations chapter), but when built and deployed via the GitHub action, only the citations show up. 

I'd be interested in the feedback of others who try to build the docs locally and what they see.

**Comment by jdebacker** [comment]
Many of the issues with references noted above were fixed after the `references.bib` file was added in PR #619.

**Comment by MaxGhenis** [comment]
Thanks @jdebacker, I updated the original https://github.com/PSLmodels/OG-USA/issues/613#issue-674018823 to be a checklist and checked the citation fixes.

**Comment by jdebacker** [comment]
Checked off a few above with PR #620 -- fixing some footnotes and cross-references.  @prrathi is going to address some others.

**Comment by jdebacker** [comment]
@MaxGhenis @prrathi How are we on the above items after some recent PRs?

**Comment by MaxGhenis** [comment]
Almost all clear, just three things left:

http://pslmodels.github.io/OG-USA/content/api/public_api.html shows at the bottom
![image](https://user-images.githubusercontent.com/6076111/97134191-c4de9c80-1709-11eb-8c79-43c18033592f.png)

http://pslmodels.github.io/OG-USA/content/theory/firms.html shows at the bottom
![image](https://user-images.githubusercontent.com/6076111/97134239-e9d30f80-1709-11eb-9c74-3f7a630c877f.png)

http://pslmodels.github.io/OG-USA/content/theory/equilibrium.html shows at the top
![image](https://user-images.githubusercontent.com/6076111/97134254-fb1c1c00-1709-11eb-905d-7e39db9c7a3b.png)

**Comment by jdebacker** [comment]
PR #672 addresses all issues noted above *except* for those in `public_api.rst`.  The rendering of the list of module names at the bottom of the generated html page seems to be an artifact of an issue with Sphinx docs in Jupyter-Book.   Closing for now, but we should revisit this if it remains in updated versions of Jupyter-Book.
