### ISSUE TITLE
Document tax_func_type values

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#616]
Currently `tax_func_type` is documented in the [Tax functions API page](http://pslmodels.github.io/OG-USA/content/api/txfunc.html?highlight=tax_func_type), but this lacks explanation of how each of the tax function types differ and what params each requires. DEP seems to be described in the [Tax functions theory page](http://pslmodels.github.io/OG-USA/content/calibration/tax_functions.html#fitting-tax-functions) so the API documentation could point there, though (unless I'm misreading the theory page), other tax function types would need to be described elsewhere.

**Comment by jdebacker** [comment]
Closed with  PR #681.
