### ISSUE TITLE
OG-USA developer meeting agenda 8/11/2020

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#618]
(Unless there isn't one? Adding as @jdebacker is out of town and I wanted to reserve some time to discuss UBI and income elasticities if possible.)

Meeting info from last time:
>10-11am ET
Zoom Meeting ID: 407 395 8475
Zoom Meeting Password: ogusa
Zoom Meeting URL: https://riceuniversity.zoom.us/j/4073958475
This meeting is open to the public.

**Comment by jdebacker** [comment]
@MaxGhenis I'm not sure if this meeting happened, but let me know if you want to discuss some of your recent UBI runs.  Glad to set up a call.

Closing this issue.
