### ISSUE TITLE
Large file storage

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#623]
To run the full suite of tests for OG-USA one needs two files that cannot be checked into the repo:
1. `puf.csv` -- cannot be checked in due to confidentiality of the data.
2. `ogusa/tests/test_io_data/tax_func_loop_inputs_large.pkl` -- cannot be checked in because the file size (~124MB) exceeds the 100MB limit on GitHub.

If we want to version control (2), we could look into [Git Large File Storage Options](https://docs.github.com/en/github/managing-large-files/about-git-large-file-storage).

If we just want others to be able to access this file, we could have the test calling this data file reach out to the file stored on the web.  Some options for storage:
1. Dropbox
2. Google Drive
3. Jason's personal website
4. An Amazon s3 bucket

The additional cost of the 1st 3 is zero, but performance (e.g., download speeds) maybe best with (4)?

cc @rickecon

**Comment by rickecon** [comment]
@jdebacker thanks for this clarifying issue. I think we should have three tiers of unit tests:

1. `CI` tests: tests that run upon commit to master of main repository
2. `full_run_a` tests: Includes all the CI tests plus all the non-CI tests minus any tests that use `puf.csv`.
3. `full_run_b` tests: Includes all the tests: `full_run_a` + tests that use `puf.csv`.

For now, I agree with your comment on the PSL Community call today, that it is nice to have all the testing data files as part of the repository. And it would be nice if we could get away with including those testing datafiles in the forthcoming conda package.

For `full_run_a` tests, we could post the `tax_func_loop_inputs_large.pkl` file in a Google Drive folder and have the tests that require that file download it using the `requests` library. This approach is clunkier than the Amazon s3 bucket, but it is only one file and should be fine. It would also be nice to specify the tests that use that file to search for it in an ignored folder on the local hard drive first, such as `ogusa/tests/test_io_data/ignored/tax_func_loop_inputs_large.pkl`. That way, we could include that folder in the `.gitignore`, but we could also run the `full_run_a` tests without having to wait for a  125MB download.

Finally, the `full_run_b` tests will search for the `puf.csv` on the local hard drive in the default `ogusa/puf.csv` path. The alternative would be to have all the testing files and the model on a secure server, where the user could run the test on the confidential data and only see the output. But I don't think we want to do that right now.

**Comment by jdebacker** [comment]
@rickecon thanks for the reply.  I like your suggestions, but a few idea/clarifications:

Rather than `test_a`, `test_b` we might want to use more descriptive names like: `long_running_test` and `requires_puf` (or similar)
 
> And it would be nice if we could get away with including those testing datafiles in the forthcoming conda package.

My idea was that those cloning the repo intend to use the source code and therefore should have all the test files (and therefore a longer download).  These folks will have to deal with the larger download that entails.  Those who just want to use the model could download the conda package, which *would not have* the bloat from these testing files.

I like your suggestions for searching for the local file.  I do not yet know how to implement the "search for `puf.csv` and if it doesn't exist, skip that test", but I'm sure it's possible.

**Comment by chusloj** [comment]
@jdebacker @rickecon If all elements of `ogusa/tests/test_io_data/tax_func_loop_inputs_large.pkl` are `numpy` or `pandas` objects, then using multiple HDF5 datastores could be a solution to uploading the contents of this pickled file to GitHub.

**Comment by jdebacker** [comment]
@chusloj Good suggestion.  I'm assuming standard library objects should be fine as well, and if that's the case, this should work.

**Comment by chusloj** [comment]
@jdebacker From what I read [here](https://docs.h5py.org/en/latest/faq.html#what-s-the-difference-between-h5py-and-pytables), `HDF5` is primarily for `numpy` data structures and anything built on them, so I'm not sure about support for standard library objects.

**Comment by chusloj** [comment]
Also, is the `tax_func_loop_inputs_large.pkl` compressed?

**Comment by jdebacker** [comment]
@chusloj - it is not.

**Comment by chusloj** [comment]
> @chusloj - it is not.

My comment seems to have disappeared, but this is referring to whether the pickle file is compressed.

**Comment by rickecon** [comment]
I have not tried this, but when I worked with `HDF5` database format back in my optimal sales tax global solution method work, it was clear that `HDF5` was best for array-liken objects. I will be surprised if it works well at compressing other Python standard library objects. @jdebacker @chusloj

**Comment by chusloj** [comment]
@rickecon Just for future reference, I found a new package called [`hickle`](https://github.com/telegraphic/hickle) that uses the `pickle` framework/API for the `HDF5` format.

**Comment by rickecon** [comment]
@chusloj . Whoa. This could be a game changer. Thank you for passing this along.

**Comment by jdebacker** [comment]
Closed with PR #688
