### ISSUE TITLE
Calibrate transfers by s,j

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#627]
Transfers are currently split uniformly across each group.

**Comment by jdebacker** [comment]
Improving this calibration would be excellent.  Do you have a suggested approach?

In the [OG-USA-Calibration repo](https://github.com/jdebacker/OG-USA-Calibration) there are files to read the PSID and compute our lifetime earnings groups from those data.  One could also draw upon the PSID for some information about benefits programs and then compute shares of total benefits by age and lifetime income group.

An alternative could be to have less precision in the lifetime income group and use cross-sectional data with more benefits details to compute shares of total transfer spending by age and income percentile (which would then be mapped to lifetime income group).

**Comment by MaxGhenis** [comment]
Looking through OG-USA-Calibration, it seems like transfer programs are loaded from the PSID, but not used, i.e. lifetime income doesn't count it. Is that right?

It also doesn't look like the PSID has Medicaid or Medicare enrollment, at least for [more recent years](https://docs.google.com/spreadsheets/d/1DswIg9pmOIesuF-a5vdBft4hwtIky0jmGzKtMwZskLE/edit#gid=74477331)..

I also wonder if using the PSID could give too much weight to how transfer programs were set up in the past. Viewing the programs more as exogenous policies would justify the cross-sectional approach.

Could you share where total transfers come from? I couldn't find it.

**Comment by jdebacker** [comment]
@MaxGhenis asks:

> it seems like transfer programs are loaded from the PSID, but not used, i.e. lifetime income doesn't count it. Is that right?

Right, our lifetime income concept is earned income only.  We are using it to define earnings abilities.

> using the PSID could give too much weight to how transfer programs were set up in the past. Viewing the programs more as exogenous policies would justify the cross-sectional approach.

Sure, but the PSID will help you define lifetime income groups (which you need a panel to do precisely) and then you can use just the latest year as a cross-section to define transfers across households under recent policy.

> Could you share where total transfers come from? I couldn't find it.

You'd have to look more into [the PSID documentation](https://simba.isr.umich.edu/VS/s.aspx) as I haven't used the PSID to gather information on transfers before.  The code may pull some variables on transfers, but I haven't included them in any analysis yet.

**Comment by MaxGhenis** [comment]
> Right, our lifetime income concept is earned income only. We are using it to define earnings abilities.

Yep, just confirming PSID transfers aren't used for other purposes?

> Sure, but the PSID will help you define lifetime income groups (which you need a panel to do precisely) and then you can use just the latest year as a cross-section to define transfers across households under recent policy.

👍 

> You'd have to look more into [the PSID documentation](https://simba.isr.umich.edu/VS/s.aspx) as I haven't used the PSID to gather information on transfers before. The code may pull some variables on transfers, but I haven't included them in any analysis yet.

I meant where OG-USA gets total transfers currently. It doesn't look like it's from PSID.

**Comment by jdebacker** [comment]
@MaxGhenis clarifies:
> I meant where OG-USA gets total transfers currently. It doesn't look like it's from PSID.

We are calibrating total transfers as a fraction of GDP and uniformly distributing that across households.  Details on the calibration of the parameter that represents the fraction of GDP that are transfers can be found in Issue #254.

**Comment by jdebacker** [comment]
@MaxGhenis See [this script](https://github.com/PSLmodels/OG-USA-Calibration/blob/master/BequestTransmission/bequest_tabs.py) to calibrate these transfers using the PSID over in the OG-USA-Calibration repo.  It may need some work - getting some different results depending on the transfer variable(s) used and those differences don't necessarily seem to correspond to what I would think given the variable descriptions.

**Comment by jdebacker** [comment]
Closing this issue here.  Discussion can continue over in the[ OG-USA-Calibration repo](http://github.com/PSLmodels/OG-USA-Calibration/).
