### ISSUE TITLE
Tax function code consolidation

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#630]
As I work through PR #629, I've been thinking about how we compute tax rates from the tax function parameters in OG-USA.  There is some duplicate code in the model as `txfunc.get_tax_rates()`, `tax.MTR_income`, and `tax.ETR_income` all use similar lines to compute tax rates from the tax function parameters.

This not only duplicates lines of code, but makes updates to the model (e.g., adding or changing tax functions) more difficult because these functions need to be changed in multiple places.

One difficulty in consolidating these functions is that (at least in the case of the DEP functional form) the parameters are in a different order in `txfunc.get_tax_rates()` than in the `ogusa.tax` functions.  E.g., for a DEP function, `txfunc.get_tax_rates` expects parameters to be in the order `A, B, C, D, max_x, max_y, share, min_x, min_y, shift, shift_x, shift_y`.  Whereas in the `ogusa.tax` functions, the model expects the order `A, B, C, D, max_x, min_x, max_y, min_y, shift_x, shift_y, shift, share`.

To fix this, I'd like to keep parameters (in the case of the DEP form) in the order `A, B, C, D, max_x, max_y, share, min_x, min_y, shift, shift_x, shift_y` throughout OG-USA.  This order is helpful since the parameters that are not estimated through the tax function estimation, `min_x, min_y, shift, shift_x, shift_y`, are appended to those that are.  This ordering helps to reduce lines of code and reordering or parameters in the tax function estimation.  

If we do this reordering, we can have on `get_tax_rates()` function that is called in `ogusa.txfunc` and `ogusa.tax`, reducing duplicate code and making updates easier.

One issue with changing this, is we break backwards compatibility with tax function parameters that have been estimated previously.

@rickecon Are you ok with breaking compatibility?  Any suggestions on better approaches to consolidating the code?

**Comment by rickecon** [comment]
@jdebacker. I think this consolidation is a great idea, and I am fine with breaking backwards compatibility (we are still pre-version-1.0).

**Comment by jdebacker** [comment]
This issue was resolved with PR #629.
