### ISSUE TITLE
Add documentation section on calibrated parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#632]
Most are currently documented in `notes` fields in `default_parameters.json`, e.g.:

https://github.com/PSLmodels/OG-USA/blob/2ad7dceda070426dfb71128222b0abcafd5eda3d/ogusa/default_parameters.json#L9-L14

`alpha_T`, `alpha_G`, and `initial_debt` are specified per https://github.com/PSLmodels/OG-USA/issues/254#issuecomment-273864494.

This issue is to add a new Jupyter Book page within the calibration section on these parameters.

**Comment by jdebacker** [comment]
This was addressed in PR #663
