### ISSUE TITLE
OG-USA and Tax-Calculator 3.0 with PUF

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#635]
I've tried to run OG-USA with Tax-Calculator 3.0 and the most recent `taxdata` enhanced PUF (Released August 21, 2020) as the micro data source.  This run fails to find the SS equilibrium under the baseline policy:

```
GE loop errors =  -0.003869952396713505 [0.0136644  0.01949733 0.02038274 0.01252643 0.01496713 0.01810716
 0.00361574] 0.007994848211199258 -0.041874426667338524
Traceback (most recent call last):
  File "create_baseline_tax_pickles.py", line 80, in <module>
    main()
  File "create_baseline_tax_pickles.py", line 74, in main
    runner(**kwargs)
  File "/Users/jason.debacker/repos/dynamic/ogusa/execute.py", line 78, in runner
    ss_outputs = SS.run_SS(spec, client=client)
  File "/Users/jason.debacker/repos/dynamic/ogusa/SS.py", line 563, in run_SS
    raise RuntimeError('Steady state equilibrium not found')
RuntimeError: Steady state equilibrium not found
```

I have no problem solving the model when the micro data source is the CPS-based file.

**Comment by rickecon** [comment]
@jdebacker. I think this is resolved by PR #637, right?

**Comment by jdebacker** [comment]
@rickecon This is *not* resolved.  All tests pass and I can successfully run `run_ogusa_example.py`, but none of this estimates tax function with the PUF and then tries to solve the model.  When I try to do this, I still get a failure to solve for the SS.

**Comment by jdebacker** [comment]
Update, here's a picture showing tax functions estimated for the baseline policy in TC 3.0.0 with the most recent PUF and the CPS datafiles (the scatter points are binned data from the PUF):

![test_funcs](https://user-images.githubusercontent.com/10715924/95664442-e0488580-0b15-11eb-84bb-a9d0f5a5fd65.png)

It appears that something in the PUF is causing the estimated tax functions to be off by quite a bit and this is probably what causes the failure of the model to solve.

**Comment by jdebacker** [comment]
I just tested this with non-age-specific DEP functions (and TC 3.0 with the PUF) and also found the SS fail to solve:
```
GE loop errors =  -0.004956054049728528 [0.01885777 0.01918287 0.02092605 0.01284355 0.01531511 0.01821569
 0.00352753] 0.009880640385368476 -0.044192095922438224
GE loop errors =  -0.004183765531131159 [0.01638258 0.019297   0.02105034 0.01291977 0.0154059  0.01832377
 0.0035485 ] 0.009170828250819552 -0.043419051928885524
GE loop errors =  -0.003797834478786233 [0.01514527 0.01935472 0.02111322 0.01295835 0.01545188 0.01837846
 0.0035591 ] 0.008814491286961122 -0.04303263820811849
GE loop errors =  -0.0036049244100199856 [0.01452667 0.01938373 0.02114485 0.01297775 0.01547501 0.01840597
 0.00356443] 0.008635982640586827 -0.04283945288521679
Traceback (most recent call last):
  File "test_nonage_spec.py", line 126, in <module>
    main()
  File "test_nonage_spec.py", line 74, in main
    runner(**kwargs)
  File "/Users/jason.debacker/repos/dynamic/ogusa/execute.py", line 78, in runner
    ss_outputs = SS.run_SS(spec, client=client)
  File "/Users/jason.debacker/repos/dynamic/ogusa/SS.py", line 563, in run_SS
    raise RuntimeError('Steady state equilibrium not found')
RuntimeError: Steady state equilibrium not found
(ogusa-dev) jason.debacker@x86_64-apple-darwin13 run_examples %
```

**Comment by jdebacker** [comment]
Non-age-specific solves when changing guess of SS `r` from 0.649 to 0.04.  I moved the guess of `r` down for this test because the tax function estimates above show a much lower rate estimated from the PUF than CPS, which would mean more capital accumulation and lower interest rates.

**Comment by jdebacker** [comment]
The SS solves with age specific functions with an initial guess of r = 0.04 as well.

Looks like just a change in starting values solves the problem.  I'll close this issue, but we should keep an eye on the tax functions given the differences in them between the CPS and PUF data.  But we can explore that in another issue.

cc @rickecon
