### ISSUE TITLE
Export table of dollar values in Compute Studio output

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA#642]
Currently, the tables and charts all show deltas from a baseline for the given OG-USA parameters. This isn't very helpful if you want to see the effect of changing an OG-USA parameter itself. For example, all deltas [here](https://compute.studio/PSLmodels/OG-USA/143/), where the only reform was changing the parameters to a small economy, are zero.

A helpful addition would be a table of actual values in the reform, which could then be used to compare between different OG-USA parameter "baselines".

This is relevant for considering the effect of changing the capital income share, given current tax parameters. cc @prrathi

**Comment by jdebacker** [comment]
@MaxGhenis If you click the download link, you get a CSV file with all the aggregate quantities and prices for both the baseline and reform.  Do you want more than what is there?  If so, we can add some more detail or additional CSV files.

**Comment by MaxGhenis** [comment]
Perfect, thanks @jdebacker. I'd thought the CSVs only had the specific numbers in the tables.

**Comment by MaxGhenis** [comment]
@jdebacker it looks like the CSVs output data in model units. Could it report dollar values instead? I retitled this issue accordingly.

In the meantime, is the dollar-model-unit multiplier the same across all models? @prrathi and I used CS exports to compare a baseline model with the default capital income share of 0.35 to another baseline with capital income share of 0.4 ([spreadsheet](https://docs.google.com/spreadsheets/d/1kdDF7sBE643KsG3xci4piQV0coH9dNs54EkKy66kDXY/edit#gid=773443129)) and we weren't sure if it's valid.

**Comment by jdebacker** [comment]
@MaxGhenis OG-USA doesn't currently produce dollars estimates.  If you use the `cbo` option on some plotting utilities, you will get dollar values where the baseline is set to hit the CBO forecast.

Not having done a lot of looking model outputs in dollar values, I am not sure we are ready to make them a default output on C/S.  Thoughts @rickecon?

In a recent run of OG-USA, the baseline seems to convert model units to 2021 dollars and get's reasonably close:
```
N = 240  # my guess at number of households in the US, in millions
base_tpi['Y'][0]*base_ss['factor_ss']*N
--------------------------
21447885.884915948
```

This $21.4T is pretty close to the [CBO forecast from April 2020](https://www.cbo.gov/publication/56335) of $21.3T.

Re the dollar multiplier units being the same. The multiplier, `factor_ss`, may vary if you change any parameters.  The way one would convert model units to GDP would be:
* For household level, dollar value variables: `dollar_val = model_val *  factor_ss * np.exp(g_y * t)`, where `t` is the number of years from the model start year.
* For economy-wide aggregate, dollar value variables: `dollar_val = model_val *  factor_ss * np.exp(g_y * t) * N_t`, where `t` is the number of years from the model start year and `N_t` are the number of households in the economy at time `t` (Note that OG-USA stores population growth rates in the `g_n` variable, but normalizes the population to 1 in the base year.  So to get `N_t` you can find the number of households in the start year (outside of OG-USA) and grow that number by the population growth rate from the model).

Finally, note that all values will be in constant dollars, with the base year being the start year of the model.

In your case, when changing the capital income share, you will need to apply separate multipliers to each model to convert to dollar values, but you can reliably compare changes in model units or ratios across these simulations.

**Comment by MaxGhenis** [comment]
Thanks for the formulas for using the Python API. Sounds like the Compute Studio output doesn't provide enough information for these computations right now though, is that right?

>In your case, when changing the capital income share, you will need to apply separate multipliers to each model to convert to dollar values, but you can reliably compare changes in model units or ratios across these simulations.

It would be reliable to, for example, compare model units with different multipliers in order to estimate the effect of a higher capital income share on GDP?

**Comment by MaxGhenis** [comment]
Per today's discussion, this is best done in the Python API, where, unlike C/S, a reform can have different model parameters from the baseline, while ensuring consistent model units.
