### ISSUE TITLE
Some math and citations/footnotes not properly rendering in docs

### ISSUE THREAD

**Issue by chusloj** [PSLmodels/OG-USA#643]
The following pages from the documentation have issues with rendering `LaTeX` equations:

- Stationarization
- Equilibrium
- Exogeneous parameters
- Demographics
- Lifetime earnings profiles

---
Additionally, There are some citations in the _Equilibrium_ section and multiple footnotes throughout the docs that aren't rendering correctly because citation syntax specific to Jupyter Book is not implemented.

**UPDATE**: The citations in the _Equilibrium_ section are missing because the references are not in the bibliography @rickecon . They are the following:

- Book: AuerbachKotlikoff:1987
- Appendix II: NishiyamaSmetters:2007
- Sec 3.1: EvansPhillips:2014
- Ch. 17: StokeyLucas1989

**Comment by chusloj** [comment]
Updated math, figures and tables are addressed in PR #644 .

**Comment by jdebacker** [comment]
@chusloj Did PR #650 fix all these issues?

**Comment by chusloj** [comment]
@jdebacker #650 did not fix all of these issues – the one issue remaining is the 4 missing citations in the _Equilibrium_ section, which are missing because they appear to be missing from the bibliography.

**Comment by chusloj** [comment]
@jdebacker solved the last issue I mentioned [here](https://github.com/PSLmodels/OG-USA/issues/643#issuecomment-716552157) in #671. Closing.
