### ISSUE TITLE
Inner/Outer loop confusion in docs

### ISSUE THREAD

**Issue by chusloj** [PSLmodels/OG-USA#659]
In the [Stationary Steady-state Solution Method](https://pslmodels.github.io/OG-USA/content/theory/equilibrium.html#stationary-steady-state-solution-method) section of the docs, the following passage mentions the outer loop twice. The text in question is at the end of the 1st paragraph of this section:

> We call these four steady-state variables the “outer loop” variables in our steady-state solution method and the determination of a fixed point over these variables the ``outer loop’’ of the steady-state solution method. The outer loop variables are the macroeconomic variables necessary to solve the household’s problem.

**Comment by rickecon** [comment]
@chusloj . Thanks for finding this poorly worded couple of sentences.

@jdebacker . The second sentence quoted above is fine. I see the weird wording in the first sentence.
> We call these four steady-state variables the “outer loop” variables in our steady-state solution method and the determination of a fixed point over these variables the ``outer loop’’ of the steady-state solution method.

I think a good fix for both sentences is the following:
> We define the four steady-state variables $\bar{r}$, $\overline{BQ}$, $\overline{TR}$, and $factor$ as "outer loop" variables. The outer loop variables are the smallest set of macroeconomic variables necessary to solve each household’s lifetime problem independently. Our solution method for the steady-state iterates on the four outer loop variables until we find the unique fixed point.

Let me know if you think my proposed fix is good, and I'll submit a PR.

**Comment by rickecon** [comment]
I just submitted PR #661 adding my suggested change to the `equilibrium.md` documentation paragraph. @jdebacker

**Comment by rickecon** [comment]
This issue is fixed by PR #661.
