### ISSUE TITLE
Household interest rate question

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#677]
@jdebacker. I think we are calculating the household interest rate incorrectly in [equation (27)](https://pslmodels.github.io/OG-USA/content/theory/government.html#government-budget-constraint) in the documentation and in the steady-state calculation in [line 157 of SS.py](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/SS.py#L157). I think we should be using the domestic debt `D_d` instead of total debt `D` and domestically held capital `K_d` instead of total capital stock `K`.

**Comment by jdebacker** [comment]
@rickecon - I think you mean Equation 27, correct?

If so, I agree that you *could* compute this differently. But we are making a simplifying assumption - that `r_hh` is computed using the ration of `K` and `D` (not `K_d` and `D_d`).  This assumption is noted in the paragraph preceding Equation 27 and the code and theory are consistent with that.

The alternative assumption, that `r_hh` is a function of `K_d` and `D_d` is fine, but would add at least one additional variable to the outer loop (namely, `K_d`).

Also, note that we are already making an even bigger assumption about household portfolio decisions - that they are not influenced by the wedge between the interest rate on public debt and private capital.  We had discussed an alternative approach (see Issue #435), but decided to keep things simple.  The simplifying assumption, that households demand `K` and `D` in whatever ratio is necessary to clear those asset markets, seems to make the assumption you note about the determination of interest rates more innocuous (after all, we are punting on totally endogenizing interest rates, asset markets, and portfolio decisions).

**Comment by rickecon** [comment]
Yes. I meant equation (27). That is a great explanation. Thanks.
