### ISSUE TITLE
Interest rate in goods market clearing condition

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#685]
The goods market clearing condition for the partially open economy default specification of `OG-USA` is currently described in the [Resource Constraint](https://pslmodels.github.io/OG-USA/content/theory/open_economy.html#resource-constraint) section of the [Open Economy Options](https://pslmodels.github.io/OG-USA/content/theory/open_economy.html) chapter of the documentation. The stationary version at the end of the section is the following.

<img width="721" alt="ResourceConstraint" src="https://user-images.githubusercontent.com/4317690/101409912-ce782a00-389b-11eb-8b69-3632d1cb5d17.png">

Why do we use `r_{hh,t}` in the resource constraint rather than the rental rate of capital `r_t` on the foreign private capital inflows `K^f_t` term and the government interest rate `r_{gov,t}` on the foreign debt holdings of government bonds `D^f_t`, respectively?

**Two Questions**
1. Is the following argument correct? The only justification I can see for our current approach of using `r_{hh,t}` in this equation is that we have to mathematically because we use `r_{hh,t}` in the household budget constraint. That is, we assume that households are indifferent between private capital and public debt despite the interest rate wedge, so we calculate `r_{hh,t}` and give them that return, which is an approximation of their composite return. Because the firms pay `r_t` to both foreign and domestic suppliers of capital and because the government pays `r_{gov,t}` to both foreign and domestic holders of bonds, we have to do the same approximation for the foreign return.

2. And am I right that it would be mathematically incorrect to keep the household budget constraint as a function of `r_{hh,t}` and in the resource constraint to change the return on private capital to foreigners to `r_t` and to change the return on government bonds to `r_{gov,t}`?

**Comment by jdebacker** [comment]
@rickecon - good question.  This appears to be a typo.  We should be using `r_t` in the resource constraint, as the code specifies [here](https://github.com/PSLmodels/OG-USA/blob/67847fcaad5c8903f13f9b46741b73abd5b46a3b/ogusa/aggregates.py#L379).

**Comment by jdebacker** [comment]
@rickecon Following up on this, we do use `r_hh` as the interest rate on `D_f` [here](https://github.com/PSLmodels/OG-USA/blob/67847fcaad5c8903f13f9b46741b73abd5b46a3b/ogusa/SS.py#L380).  I think I recall something where given how we allocate the portfolio of domestic savers between K and D, this was necessary.  I'll try to dig up any derivations I might have.

**Comment by rickecon** [comment]
@jdebacker. Your first comment is incorrect. In both `SS.py` and `TPI.py` we use the `r_{hh,t}` to calculate both the return for foreign private capital (see [line 383](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/SS.py#L383) of `SS.py` and [line 680](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/TPI.py#L680) of `TPI.py`) and also the return on holding government debt. `OG-USA` uses `r_{hh,t}` to calculate the debt service portion of the resource constraint in both `SS.py` [line 380](https://github.com/PSLmodels/OG-USA/blob/67847fcaad5c8903f13f9b46741b73abd5b46a3b/ogusa/SS.py#L380) and in `TPI.py` [line 676](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/TPI.py#L676). This makes sense to me as capturing the remaining payments not paid to domestic households for the two types of capital because the `r_{hh,t}` paid to them is an approximation. Therefore, we are obliged to use `r_{hh,t}` as the payment to foreigners.

I think I am convinced that it would NOT be equivalent to change the resource constraint to have `r_t` as the return on private capital and to have `r_{gov,t}` be the return on holding government debt while giving household the return on their savings of `r_{hh,t}`.

**Comment by jdebacker** [comment]
@rickecon You are right - thanks for pointing my error. 

> This makes sense to me as capturing the remaining payments not paid to domestic households for the two types of capital because the r_{hh,t} paid to them is an approximation. Therefore, we are obliged to use r_{hh,t} as the payment to foreigners.

This is what I recall.  But I don't seem to have electronic copies of my derivations and the hand written notes are in my office somewhere.  It'd be good to write this out again.

**Comment by rickecon** [comment]
@jdebacker. Thanks so much for getting this right when you implemented this partially open economy module after the CBO OG conference. I didn't know that I didn't know this. This is nontrivial, and it was a great exercise for me to go through the theory and reasons why.

**Comment by rickecon** [comment]
This is updated in the documentation in open WIP PR #683.
