### ISSUE TITLE
Confirm that stationarized foreign debt law of motion is incorrect in documentation

### ISSUE THREAD

**Issue by rickecon** [PSLmodels/OG-USA#687]
@jdebacker. I wanted to confirm that the partially open economy stationarized foreign debt holdings law of motion in the [Foreign Debt Purchases](https://pslmodels.github.io/OG-USA/content/theory/open_economy.html#foreign-debt-purchases) section of the [Open Economy Options](https://pslmodels.github.io/OG-USA/content/theory/open_economy.html) chapter of the current documentation is incorrect. It is currently displayed as the following.

<img width="563" alt="Screen Shot 2020-12-08 at 1 21 26 AM" src="https://user-images.githubusercontent.com/4317690/101458137-b9c78080-38f3-11eb-84b3-69ff5bf6bac6.png">

However, my math shows that it should be the following.

<img width="476" alt="Screen Shot 2020-12-08 at 1 22 52 AM" src="https://user-images.githubusercontent.com/4317690/101458295-eed3d300-38f3-11eb-887e-8589a171da74.png">

The only difference is that I think your `g_{n,t+1}` should be changed to `1 + \tilde{g}_{n,t+1}`. I find that this value in the code `new_borrowing_f` is specified in the way I describe above and not the way that is currently shown in the documentation.

**Comment by jdebacker** [comment]
@rickecon I agree - typos in the docs.

**Comment by rickecon** [comment]
@jdebacker . OK. I have fixed this in open PR #683.
