### ISSUE TITLE
Create "uses puf" flags for tests

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/OG-USA#716]
Currently we have markers for "full run" and "regression" tests.  It maybe helpful to decompose the "full run" group into those that require the PUF and those that take a long time to run.  This would be useful because contributors without the PUF should run the longer running tests (that are too long for CI testing in GH Actions) locally, but they may be unable to run the PUF-based tests.

**Comment by rickecon** [comment]
@jdebacker. Yes. That will work fine. I agree.

**Comment by jdebacker** [comment]
Addressed in PR #718
