### ISSUE TITLE
Consolidate Graphing?

### ISSUE THREAD

**Issue by evan-magnusson** [PSLmodels/OG-USA#92]
Currently, we have 2 main graphing files, SS_graphs.py and TPI_graphs.py.  However, we also do some graphing in demographics.py, income.py, wealth_data.py, and labor_data.py.  These other graphing functions are controlled by a flag, but perhaps it might be best to move all of these graphing functions into SS_graphs.py.  That way, all graphing occurs in one place.
     This should be pretty easy for income.py, wealth_data.py, and labor_data.py, since what they graph is saved anyway.  However, for demographics.py, some of the objects it graphs are not currently saved.  This is easily changed, but it will need to change in order for another separate function to graph the fertility rates and immigration rates, for example.
    This isn't terribly important, but might be something to think about in a later version.

**Comment by jdebacker** [comment]
@rickecon How to you feel about this suggestion?

I like it because it:
1) Reduces the lines of code in any script.  Pulling out the graphing commands will make it easier to read the executable code.
2) By putting all the graphs in one place, we might be more likely to reduce the lines of code by doing things like creating a [style sheet](https://matplotlib.org/users/style_sheets.html) or making a plotting function flexible so that it can handle multiple inputs.
3) We've talked about something related to this recently - having a script to produced more detailed output (tables and figures) from OG-USA runs (such as the script you created for the QNs).

This will take some time to map out what objects will need to be saved, etc., but I think it could be helpful.

**Comment by jdebacker** [comment]
Not quite 4 years later, I plan to get started on this.   The outline is the following:

Have 4 different modules:
1. OG-USA parameter plots (takes parameter class as argument)
  * Plot of lifecycle earnings profiles
  * Plot of initial and adjusted immigration rates
  * Plot of initial and SS population distribution (and maybe some along the way)
  * Plot of mortality rates by age
  * Plot of fertility rates by age
  * Plot pop growth rate by year with ss value
  * Plot of elliptical utilty vs constant frisch
    * Plot can do marginal or levels of utility
  * Plot ETR/MTRs by income
  * 3D plot of surface of tax functions with scatter plot of ETR data
  * 3D scatter plot of tax function data
2. OG-USA parameter tables (takes parameter class as argument)
  * Table with all model parameters
  * Mean ETR/MTRs over budget window
3. OG-USA output plots (takes paths to output as arguments, maybe also number of periods)
  * Plot percentage change in macro vars (several together - Y, L, K or I, G, C)
  * Plot fiscal vars pct diff (G, D, etc)
  * Plot time path fo debt/GDP for baseline and reform
  * Percentage change in factor prices (r, w)
  * Plot of macro vars, baseline vs reform (one var only, factor prices too)
  * 2D plots of lifecycle profile of c, n, y, b by ability type in SS
  * 2D plots of percentage changes in lifecycle profile of c, n, y, b by ability type in SS
  * 3D distribution plots like [OSE lab plot](https://www.oselab.org/gallery/overlapping_generations) with animation of time path
  * Bar graphs with percentage change in b, n, c, after-tax-income, etc by percentile group
    * For SS
    * For some N year range over the time path (default to first first 5)
  * Bar graphs with percentage change in b, n, c, after-tax-income, etc by quintile
  * SS labor supply of lifecycle, model vs data
  * Plot of lifecycle wealth from model - separate plots by ability
  * Plot of gini coeffient in diff vars over time path
4. OG-USA output tables
  * Percentage changes in macro vars over the budget window
  * Wealth distribution moments from the model and data
  * Table with gini coefficients in SS
  * Table with other inequality measures, baseline vs reform

**Comment by jdebacker** [comment]
Adding the proposed graphs and tables was begun with PR #461.

**Comment by jdebacker** [comment]
Opened by @evan-magnusson as an undergraduate and now closed as he goes on the PhD job market!

Final plotting calls were moved with PR #525.
